export const VITE_SUPABASE_URL="https://duynqbjwlajhpxrzxszi.supabase.co"
export const VITE_SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1eW5xYmp3bGFqaHB4cnp4c3ppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4NTUwMjgsImV4cCI6MjA1NzQzMTAyOH0.VcIijC9b2-mIwH6IU9BX3Pw21hmktBL_zYXx7qIT9KA"
